In [22]:
#question 1
import numpy as np
x=np.array([[1,2],[3,4]])
y=x.tolist()
print(y)
print(type(y))

[[1, 2], [3, 4]]
<class 'list'>


In [15]:
#question2
import numpy as np
x=np.array([[1,2,3],[0,1,0],[3,2,1]])
print("methode 1 ")
z=x.trace()
print(z)

print("methode 2")
a=np.diag(x)
s=0
for i in a:
    s=s+i
print(s)    

methode 1 
3
methode 2
3


In [5]:
import numpy as np
a =np.array([[1,2],[3,5]]) 
x=2
for i in range(len(a)):
    for j in range(len(a[i])):
        
        if x<a[i][j]:
            print(a[i][j])
    
    
    

3
5


In [21]:
#question 4
import numpy as np
A =np.array([[0,1],[1,0]]) 
B=np.array([[1,0],[0,1]])
c=np.array([[0,0],[0,0]])

for i in range(len(A)):
    for j in range(len(A[i])):
        c[i][j]=A[i][j]+B[i][j]
c        



array([[1, 1],
       [1, 1]])

In [12]:
#question 5
import numpy as np
print("Original matrix:\n")
X = np.random.rand(2,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.06846671 0.03078435 0.35157611]
 [0.35912432 0.67195828 0.79679841]]

Subtract the mean of each row of the said matrix:

[[-0.08180902 -0.11949137  0.20130039]
 [-0.25016935  0.06266461  0.18750474]]
